### ISSUE TITLE
Rename `triggerComponentKey` to relate to the `fractal` module?

### ISSUE THREAD

**Issue by sompylasar** [gcazaciuc/redux-fractal#3]
The `meta` part of the action object is a shared namespace, so the name of the key should be more unique to prevent name conflicts.

Suggest: `reduxFractalKey`

**Comment by gcazaciuc** [comment]
Renamed in 1.3 to `reduxFractalTriggerComponent`. Thanks for raising this.

**Comment by sompylasar** [comment]
:+1:
