### ISSUE TITLE
Cannot find babel module

### ISSUE THREAD

**Issue by kuon** [gcazaciuc/redux-fractal#5]
I just updated to 1.3.1, but I have the following error:

local.js:11Uncaught Error: Cannot find module 'babel-runtime/helpers/extends' from 'redux-fractal/dist/local.js'

It seems the npm module was not well packed.

**Comment by gcazaciuc** [comment]
Sorry about that. Added babel-runtime as a dependency and published 1.3.2 Can you check it works on your end ?

**Comment by kuon** [comment]
This is fixed in 1.3.2
