### ISSUE TITLE
Pass component key to createStore

### ISSUE THREAD

**Issue by kuon** [gcazaciuc/redux-fractal#9]
It would be nice to pass the component key to `createStore`.

For example:

```
local({
  key: (props) => props.id,
  createStore: (props, key) =>  createStore(rootReducer, extractInitialStateFromLocalStorage(key))
})
```

Of course, I can implement the same logic and do `props.id` in my `createStore` but I think it might be better to have the component key in `createStore`.

**Comment by gcazaciuc** [comment]
The signature of createStore is currently: (props, existingState, context) . Adding a 4th param would only complicate it only to handle a specific case.

**Comment by kuon** [comment]
Yeah, I can make a `deriveKey` and use it like:

```
local({
  key: deriveKey,
  createStore: (props, context) => createStore(rootReducer, deriveKey(props, context))
})
```

But I had a feeling `createStore` could receive it. It's your call.

**Comment by gcazaciuc** [comment]
Let's close this since there are user land approaches to the mentioned use cases.
