### ISSUE TITLE
Publish latest version to npm

### ISSUE THREAD

**Issue by justafreak** [gcazaciuc/redux-fractal#97]
Latest version from npm registry does not match the latest changes from master.

**Comment by MrLeebo** [comment]
I recently discovered this project while working on an issue with our React 16 upgrade. You can get the latest changes (with the prop-types fix) by changing your dependency to 

```    
"redux-fractal": "hoschi/redux-fractal#feature/95-build",
```

**Comment by SNikon** [comment]
@gcazaciuc Would it be possible to release a build with the latest fixes? This would be quite useful. Cheers!

**Comment by gcazaciuc** [comment]
Sure, I will update here

**Comment by gcazaciuc** [comment]
Just published 1.8.0. Let me know if everything looks ok,
